# ----------------------
# Base
# ----------------------
    FROM node:20-alpine AS base
    WORKDIR /app
    COPY package*.json ./
    RUN npm ci
    
    # Copier le reste du code
    COPY . .
    
    # ----------------------
    # Development stage
    # ----------------------
    FROM base AS development
    EXPOSE 3000
    CMD ["npm", "run", "dev"]
    
    # ----------------------
    # Production stage
    # ----------------------
    FROM base AS builder
    ARG NEXT_PUBLIC_API_URL
    ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
    RUN npm run build -- --turbo=false
    
    FROM node:20-alpine AS production
    WORKDIR /app
    COPY package*.json ./
    RUN npm ci --only=production
    COPY --from=builder /app/.next .next
    COPY --from=builder /app/public ./public
    COPY --from=builder /app/package.json ./package.json
    EXPOSE 3000
    CMD ["npm", "start"]
    